version: "3.7"

services:
  backend-api:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=mysql-db-dev
    depends_on:
      - mysql-db-dev

  mysql-db-dev:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: store
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql/dev

  frontend_dev:
    image: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    depends_on:
      - backend-api

volumes:
  mysql_dev_data: